# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5b97aa9c8c5962f561b06fcbd7e1d3469203429c1631b278ca0370370f310ae46e75d9bc17fee622784ddc50da710db52e455897c61bec19404a0242668e1ab

test:
  secret_key_base: e72bdf3be5c638ae8ab3cdf6651e9f52518cf9e6d1f4626f810c1b6da06fac7c8d8f7a0895b558c4067cded6f30665af94b1a58b01b1c34ba03c574f50e582fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
